import {
  AlertCircle,
  AlertTriangle,
  ArrowDownCircle,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpCircle,
  ArrowUpDown,
  Bitcoin,
  Bot,
  Box,
  Brain,
  Calculator,
  Calendar,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Copy,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Edit2,
  Eye,
  EyeOff,
  Filter,
  Globe,
  GraduationCap,
  History,
  Home,
  Image as ImageIcon,
  Info,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  Lightbulb,
  Loader2,
  LogOut,
  Mail,
  Maximize2,
  Merge,
  MessageSquare,
  Minimize2,
  Monitor,
  Moon,
  MoreHorizontal,
  Palette,
  Pencil,
  PieChart,
  PiggyBank,
  Plus,
  PlusCircle,
  RefreshCw,
  RotateCcw,
  Scale,
  Search,
  SearchX,
  Send,
  Settings,
  Settings2,
  Shield,
  Smartphone,
  Star,
  Sun,
  Target,
  Terminal,
  Trash,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Upload,
  User,
  Users,
  Wallet,
  X,
  XCircle,
  Zap,
  Utensils,
  ShoppingCart,
  Car,
  Heart,
  BookOpen,
  Gamepad,
  Gift,
  Plane,
  ShoppingBag,
  Coffee,
  Music,
  Film,
  Wifi,
  Map,
  Phone,
  Briefcase,
  Shirt,
  Dumbbell,
  Baby,
  Dog,
} from 'lucide-react';

export const Icons = {
  // Primitives & General
  Add: Plus,
  AddCircle: PlusCircle,
  Alert: AlertTriangle,
  ArrowRight: ArrowRight,
  ArrowLeftRight: ArrowLeftRight,
  ArrowUpDown: ArrowUpDown,
  Calendar: Calendar,
  Check: Check,
  CheckCircle: CheckCircle,
  CheckCircle2: CheckCircle2,
  ChevronDown: ChevronDown,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  Close: X,
  CloseCircle: XCircle,
  Copy: Copy,
  Delete: Trash2,
  Trash: Trash,
  Edit: Edit2,
  EditPencil: Pencil,
  Filter: Filter,
  History: History,
  Info: Info,
  Loader: Loader2,
  Menu: LayoutList,
  MoreHorizontal: MoreHorizontal,
  Refresh: RefreshCw,
  Search: Search,
  SearchX: SearchX,
  Settings: Settings,
  SettingsAdjust: Settings2,
  Star: Star,
  User: User,
  Users: Users,
  Warning: AlertTriangle,
  Error: AlertCircle,
  
  // Finance & Domain
  Bank: Landmark,
  Bitcoin: Bitcoin,
  Calculator: Calculator,
  Card: CreditCard,
  Currency: DollarSign,
  Income: ArrowUpCircle,
  Expense: ArrowDownCircle,
  Investment: TrendingUp,
  Money: PiggyBank,
  Target: Target,
  TrendingDown: TrendingDown,
  TrendingUp: TrendingUp,
  Wallet: Wallet,
  Merge: Merge,
  Undo: RotateCcw,
  
  // Navigation & Layout
  Dashboard: LayoutDashboard,
  Home: Home,
  LayoutGrid: LayoutGrid,
  Maximize: Maximize2,
  Minimize: Minimize2,
  
  // Feature Specific
  AI: Bot,
  Brain: Brain,
  Crypto: Bitcoin,
  Database: Database,
  Download: Download,
  Education: GraduationCap,
  Globe: Globe,
  Idea: Lightbulb,
  Image: ImageIcon,
  Logout: LogOut,
  Mail: Mail,
  Message: MessageSquare,
  Mobile: Smartphone,
  Moon: Moon,
  Palette: Palette,
  PieChart: PieChart,
  Scale: Scale,
  Security: Shield,
  Send: Send,
  Social: Users,
  Sun: Sun,
  Terminal: Terminal,
  Trophy: Trophy,
  Upload: Upload,
  Visibility: Eye,
  VisibilityOff: EyeOff,
  Zap: Zap,
  
  // Misc
  Box: Box,
  Clock: Clock,
  Monitor: Monitor,
  // Categories
  Utensils: Utensils,
  ShoppingCart: ShoppingCart,
  ShoppingBag: ShoppingBag,
  Car: Car,
  Heart: Heart,
  BookOpen: BookOpen,
  Gamepad: Gamepad,
  Gift: Gift,
  Plane: Plane,
  Coffee: Coffee,
  Music: Music,
  Film: Film,
  Wifi: Wifi,
  Map: Map,
  Phone: Phone,
  Briefcase: Briefcase,
  Shirt: Shirt,
  Dumbbell: Dumbbell,
  Baby: Baby,
  Dog: Dog,
};

export type IconType = keyof typeof Icons;
